### ISSUE TITLE
Certain items should not drop.

### ISSUE THREAD

**Issue by Dragonop** [everamzah/kalite#1]
Some items should not drop to the ground when digging them, because normaly one would grab it with your hand (not all the items that you can dig with the hand.), like: 
Torches, papyrus, cotton, flowers, apples, leaves, cart, ladders, rails, signs, etc.

**Comment by everamzah** [comment]
I like where this is going.  However, by the very same logic, if you're holding a pick and dig a torch, it should still drop to the ground.  Therefore consider this: If a player has nothing in their hand, and they can dig the node with their bare hand, then the node is not dropped but placed in the digger hand.

**Comment by everamzah** [comment]
83b13ef4362823f991dba924e33b2d0a4f4e26ac
